### ISSUE TITLE
Potential issue on updating the q-values in UpdateKnowledge()

### ISSUE THREAD

**Issue by MarcoMeter** [jcaramello/deepQ-stock#1]
Hey,

I just had a look at some parts of your implementation and I came across a potential issue:

[UpdateKnowledge() of the DeepRLAgent class](https://github.com/jcaramello/deepQ-stock/blob/master/DeepQStock/Agents/DeepRLAgent.cs#L263) updates all actions' values based on the experience's reward. But an experience is based on only one action, which lead to the transition of states. So the reward should only be related to the action which has been carried out. Instead of updating all action value's, you'd probably have to update only the q value of the action stored in the experience.

**Comment by jcaramello** [comment]
Hey you are right, thanks!, 

I'm still working in the project and I have to test a lot of things.

Regards.
